### PR TITLE
Add these important adjectives

### PR DESCRIPTION
**Pull request by mrkirkland**
because we all like our Brians bespectacled

### CODE REVIEW

**Comment by briandeheus** [comment]
### Byzantine
*bɪˈzantʌɪn,bʌɪ-/*
*adjective*

1. relating to Byzantium, the Byzantine Empire, or the Eastern Orthodox Church.
2. (of a system or situation) excessively complicated, and typically involving a great deal of administrative detail.

-----

I'm ok with this. 👌

**Comment by briandeheus** [comment]
Thanks for your contribution!

**Comment by ReiinGrumpyLand** [comment]
Please add "busty" to the list too! x

**Comment by briandeheus** [comment]
@ReiinGrumpyLand have no fear, it's on the list. 😃

**Pull request merged**
